services:
  postgres_local:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - petshop_network

  backend:
    # extra_hosts:
    #  - "host.docker.internal:host-gateway"  # Minha rede docker interna vai rodar utilizando a rede da minha máquina / host
    # dns:
    #  - 8.8.8.8 google
    #  - 1.1.1.1 cloudflare
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: alessaleit/pacotesbanho-backend:latest
    container_name: petshop_backend
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_local:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis:6379
      DEBUG: "true"
      LOG_LEVEL: "debug"
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    depends_on:
      postgres_local:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --log-level debug
    restart: unless-stopped
    networks:
      - petshop_network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: /api/v1
    image: alessaleit/pacotesbanho-frontend:latest
    container_name: petshop_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - petshop_network

  redis:
    image: redis:7-alpine
    container_name: petshop_redis
    networks:
      - petshop_network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: petshop_prometheus
    ports:
      - "9090:9090"
    networks:
      - petshop_network

networks:
  petshop_network:
    driver: bridge

volumes:
  pgdata:
