[pytest]
# Adiciona a pasta backend ao PATH para que 'import app' funcione
pythonpath = backend
# Define onde estão os testes
testpaths = test
# Configurações padrão de cobertura (aponta para 'app')
addopts = --cov=app --cov-report=term-missing --cov-report=html
filterwarnings = ignore::DeprecationWarning