apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101 # UID padrão do usuário nginx no alpine
      automountServiceAccountToken: false
      containers:
      - name: frontend
        image: alessaleit/pacotesbanho-frontend:1.0.3
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
        resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
              ephemeral-storage: "512Mi"
            requests:
              memory: "128Mi"
              cpu: "100m"
              ephemeral-storage: "256Mi"
        env:
        - name: API_HOST
          value: backend-service