apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  labels:
    app: recanto-mini-dogs
type: Opaque
data:
  DB_NAME: cGV0c2hvcA==
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: QWxlc3NhbmRyYTIy
  ADMIN_EMAIL: YWRtaW5AZW1haWwuY29t
  ADMIN_PASSWORD: YWRtaW4xMjM=